Add Bayesian estimation
jepusto/scdhlm pull request #113
Opened 2023-03-29 12:49 UTC by manchen07

Based on our discussion yesterday, I've added a `calc_consts()` function to the package to simply the effect size calculation code. Basically, for this current push, the Bayesian estimation is added to the package and the app. However, there are remaining issues for the app.

- I added a RUN button for RML and Bayesian. I like it because model will only run when the button is clicked instead of keep running and updating every time we change anything. One outstanding issue is that we need to find a better place for the center slider because the center point will need to be specified before running the model. One solution is to move the center slider above the RUN button.
- I added a progress indicator. It is shown at the bottom right of the screen. It just flashes for one second for RML but will show longer for Bayesian estimation. Not sure if there is a better way to indicate the progress of model fitting.

- For the Bayesian estimation

1. RUN button is now above the advanced options, which might not make sense. 
2. Under model estimates, only sample sizes and fixed effects tables are shown for now. Need to add the random effects, variance parameter, autocorrelation parameter, and information criteria.
3. Not sure why Bayesian diagnostic plots are not shown. Need to debug.

- Need to update the syntax code chunks. The outdated code chunks are causing some unit tests to fail.

I will work on the Bayesian model estimates tables, Bayesian plots, and the syntax code chunks for the rest of this week. Feel free to edit the code and push your edits. I won't push any more commits until you finish reviewing and editing. Let me know if you have any questions.

2023-03-30 01:25 UTC, manchen07 commented
I hope you haven't started to review this pull request. I've just edited the code for model estimates tables and Bayesian plots. They seem to work. I will work on the code chunks later this week. Feel free to start the review any time. I won't edit more :)

2023-03-31 02:58 UTC, jepusto commented on R/calc_BCSMD.R
> +    CI_L <- if (CI[1] < 100 & CI[1] > -100) CI[1] else format(CI[1], scientific = TRUE)
We should not be formatting the output in this function. Formatting can happen before display in the app but the r function should return numeric values.

2023-03-31 03:04 UTC, jepusto requested changes
I really like how you've simplified the structure of the package functions with calc_consts() and g_mlm_Bayes(). I think this helps quite a bit. I'm working on writing some unit tests for these functions. Will comment again when I'm done, but there will probably be some minor things for your review.

2023-03-31 03:17 UTC, jepusto commented on R/calc_BCSMD.R
> +    if (design %in% c("CMBB", "CMB")) {
Should this be `c("RMBB","CMB")`?

2023-03-31 04:12 UTC, jepusto commented
I added some unit tests for `calc_consts()`. Do you have any thoughts on how to test `g_mlm_Bayes()`? I'm stumped.

2023-03-31 15:03 UTC, manchen07 commented on R/calc_BCSMD.R
> +    CI_L <- if (CI[1] < 100 & CI[1] > -100) CI[1] else format(CI[1], scientific = TRUE)
Sure. I'll remove the formatting.

2023-03-31 15:04 UTC, manchen07 commented on R/calc_BCSMD.R
> +    if (design %in% c("CMBB", "CMB")) {
Yes... Thanks for catching that.

2023-03-31 15:25 UTC, manchen07 commented
> I added some unit tests for `calc_consts()`. Do you have any thoughts on how to test `g_mlm_Bayes()`? I'm stumped.

Thanks for adding the unit tests for `calc_consts()`. 

Regarding the `g_mlm_Bayes()`,  to calculate the denominator of BCSMD, we have now followed the tradition by calculating the `r_const` first, then multiplying `r_const` by all random effects components from the posterior draws. Previously I just grabbed the relevant random effects variance covariance from the posterior distribution.  What do you think if we compare `g_mlm_Bayes()` to the previous approach?

2023-03-31 15:33 UTC, jepusto commented
> Regarding the `g_mlm_Bayes()`, to calculate the denominator of BCSMD, we have now followed the tradition by calculating the `r_const` first, then multiplying `r_const` by all random effects components from the posterior draws. Previously I just grabbed the relevant random effects variance covariance from the posterior distribution. What do you think if we compare `g_mlm_Bayes()` to the previous approach?

Sure, that seems like it would be a good test, and it would also work as an additional check on `calc_consts()` (I think?).

2023-03-31 15:46 UTC, manchen07 commented
> > Regarding the `g_mlm_Bayes()`, to calculate the denominator of BCSMD, we have now followed the tradition by calculating the `r_const` first, then multiplying `r_const` by all random effects components from the posterior draws. Previously I just grabbed the relevant random effects variance covariance from the posterior distribution. What do you think if we compare `g_mlm_Bayes()` to the previous approach?
> 
> Sure, that seems like it would be a good test, and it would also work as an additional check on `calc_consts()` (I think?).

Yes, that's right! I'll send an update once I'm done with adding the tests.

2023-05-09 17:48 UTC, jepusto commented
Design question: Do we want to have separate s3 methods for generating a detailed summary table (like we presented in the 3-level BC-SMD paper) and for generating a one-line summary of the effect size estimate?

2023-06-14 19:33 UTC, jepusto reviewed
Is rstan needed in Suggests, given that it is a dependency of brms?

2023-06-14 20:52 UTC, jepusto reviewed
See inline comments and questions.

2023-06-14 20:52 UTC, jepusto commented on R/calc_BCSMD.R
> +#' @importFrom brms brm
I don't think we can importFrom unless a package is in Imports or Depends. You can take the @importFrom markup out since it looks like you're always calling the functions with brms::.

2023-06-14 20:52 UTC, jepusto commented on R/calc_BCSMD.R
> +#'
This needs to get wrapped in an if() so that the example only gets run if the necessary Suggests packages are installed.

2023-06-14 20:52 UTC, jepusto commented on R/calc_BCSMD.R
> +#' @importFrom brms brm
Just double check that these functions are always called with the package prefix, including in function signatures.

2023-06-14 20:52 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/es-Bayes-example-MBs.R
> +dat <- dat[,c("{user_parms}")]
Why do we need to change the variable names here, as oppose to using the names as specified in the dataset?

2023-06-14 20:52 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/es-Bayes-example-TR.R
> +
Same question as above: 
Why do we need to change the variable names here, as oppose to using the names as specified in the dataset?

2023-06-14 20:52 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/es-RML-example-MBs.R
> +dat <- dat[,c("{user_parms}")]
Same question as above.

2023-06-14 20:52 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/es-RML-example-TR.R
> +
Same question as above.

2024-09-05 22:37 UTC, manchen07 commented
Hi James,

I think the R-CMD-check and test-coverage failed on most of these systems because brms is not running. I tried to follow what brms package developers did in the R-CMD-check.yaml and test-coverage.yaml, but still could not figure out how to get brms run on these platforms...Maybe we can discuss more tomorrow. Our unit tests passed on my computer and on the devel version of ubuntu...

Man

2026-03-19 14:39 UTC, merged