Fixed the error in the app when filtering a variabe
jepusto/scdhlm pull request #58
Opened 2020-12-29 03:04 UTC by manchen07

This pull request solves the issue #57.

I found another issue from this nazdat.xlsx example. When the data set has nonstandard column names, like the space or parenthesis in nazdat.xlsx, the current replication code in the Syntax tab, if run in R or RStudio, will return a bunch of errors because `preprocess_SCD()`, `lme()`, or `graph_SCD()` functions cannot recognize the variable names. Do you suggest we add backticks to all variable names in the Syntax tab? Or we can throw an error when users specify variable names in the Load tab and ask them to rename the variables.

2020-12-29 18:15 UTC, jepusto approved these changes

2020-12-29 19:16 UTC, jepusto commented
Good catch on the variable name issue. What about using `janitor::clean_names()` as part of the data read-in process?

2020-12-30 01:47 UTC, manchen07 commented
Thanks for your suggestion of `janitor::clean_names()`. I added it to the data read-in process without identifying whether the variable names of input data include special characters. The replication code will always show this line "clean_names(case = "parsed")". I think this is easier comparing to listing all possible special characters and then cleaning the variable names if there is any special character. Please let me know if you want to do this differently.

2020-12-30 16:50 UTC, jepusto requested changes
See inline comments.

2020-12-30 16:50 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/load-excel.R
> +  clean_names(case = "parsed")
Does this need `as.data.frame()` at the end of the pipeline?

2020-12-30 16:50 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/load-from-function.R
> +# Please use janitor::clean_names(case = "parsed") if the variable names include special character(s).
The app calls `clean_names(case = "parsed")` on the loaded dataset, so I think (?) the replication code should do the same, e.g.,
```
dat <- clean_names(dat, case = "parsed")
```

2020-12-30 16:51 UTC, jepusto commented
Forgot to add: I think it's fine to just call `clean_names()` even if the names are already acceptable. 

I pushed a few small bits of tidying up, so be sure to pull before making further modifications.

2020-12-30 22:43 UTC, manchen07 commented on inst/shiny-examples/scdhlm/code-chunks/load-excel.R
> +  clean_names(case = "parsed")
Is this related to `as.data.frame()` in the data read-in process in server.R? I think we have `as.data.frame()` when reading in a .xlsx file in the app because `phases <- levels(as.factor(datFile()[,input$phaseID]))` works with a data frame not a tibble. 

In the Syntax tab, `read_excel()` returns a tibble and `preprocess_SCD()` returns a data frame which is used in model fitting and effect size calculation. The code works fine when run in RStudio without adding `as.data.frame()`.

2020-12-30 23:03 UTC, manchen07 commented on inst/shiny-examples/scdhlm/code-chunks/load-from-function.R
> +# Please use janitor::clean_names(case = "parsed") if the variable names include special character(s).
Do you mean removing "if the variable names include special character(s)" because the app always cleans the variable names even if the names are okay? I updated this message and just pushed the commit.

2020-12-31 03:06 UTC, jepusto commented on inst/shiny-examples/scdhlm/code-chunks/load-excel.R
> +  clean_names(case = "parsed")
Makes sense. Thanks for clarifying this for me.

2020-12-31 03:25 UTC, jepusto approved these changes

2020-12-31 03:28 UTC, merged